const Map words = {
  "app_title": "KumaV",
  "play_list": "播放列表",
  "play_failed": "播放失败",
  "cancel": "取消",
  "retry": "重试",
  "confirm": "确认",
  "delete_item": "删除 {1}({0})",
  "undo": "取消",
  "start_download": "开始下载",
  "can_not_download": "下载失败",
  "install_confirm": "从 {url} 克隆项目",
  "no": "否",
  "yes": "是",
  "ok": "了解",
  "account": "账号",
  "general": "通常",
  "language": "語言",
  "clone_project": "克隆中...",
  "select_main_project": "设置为主项目",
  "not_installed": "未克隆",
  "add_project_failed": "未能添加，是否已添加？",
  "new_project": "添加Git项目",
  "new_project_hint": "Git://...",
  "add": "添加",
  "remove_project": "移除项目",
  "would_remove_project": "是否移除项目({0})?",
  "credits_content": "",
  "disclaimer": "免责声明",
  "disclaimer_content": """
本软件是个加载开发者提供的插件项目，来加载网络资源并轻松观看视频的软件。软件中出现的图片资源文字，都是由插件项目以及资源网站所提供。
软件本身不提供视频服务，使用漫画资源时请遵循相关法律法规。

本软件所提供下载的视频资源，版权归原作者所有。仅供学习交流之用，请复制、下载者遵循国家相关法律、法规，在未获得版权拥有者授权之前，勿作它用；如因非法使用引起纠纷，一切后果由使用者承担。
  """,
  "credits": "贡献者们",
  "can_not_open": "不能开启 {0}",
  "framework": "Framework",
  "no_main_project": "无项目",
  "select_main_project_first": "设为主项目",
  "video_home": "熊视频",
  "history": "历史纪录",
  "favorites": "收藏夾",
  "download_list": "下载列表",
  "manage_projects": "管理中心",
  "settings": "详设细定",
  "search": "寻幽觅胜",
  "reverse_order": "逆向",
  "order": "正向",
  "libraries_hint": "克隆并选择一个项目后即可开始浏览内容。",
  "after_select_main": "已经选择 {0} 为主项目,返回 {1} 即可开始浏览。",
  "need_overlay": "开启 \"允许在其他应用的上层显示\" 以便显示小窗口播放器。",
  "sort_default": "默认排序",
  "sort_title": "标题排序",
  "sort_subtitle": "副标题排序",
  "waiting": "等待中...",
  "download_size": "下载空间",
  "cached_size": "缓存空间",
  "clear_cache": "清空缓存，请确认",
  "clear": "清空缓存",
  "source": "来源",
  "multi_thread_limit": "下载线程数",
};