const Map words = {
  "app_title": "KumaV",
  "play_list": "播放列表",
  "play_failed": "播放失敗",
  "cancel": "取消",
  "retry": "重試",
  "confirm": "確認",
  "delete_item": "刪除 {1}({0})",
  "undo": "取消",
  "start_download": "開始下載",
  "can_not_download": "下載失敗",
  "install_confirm": "從 {url} 克隆項目",
  "no": "否",
  "yes": "是",
  "ok": "了解",
  "account": "賬號",
  "general": "通常",
  "language": "語言",
  "clone_project": "克隆中...",
  "select_main_project": "設置為主項目",
  "not_installed": "未克隆",
  "add_project_failed": "未能添加，是否已添加？",
  "new_project": "添加Git項目",
  "new_project_hint": "Git://...",
  "add": "添加",
  "remove_project": "移除項目",
  "would_remove_project": "是否移除項目({0})?",
  "credits_content": "",
  "disclaimer": "免責聲明",
  "disclaimer_content": """
本軟件是個加載開發者提供的插件項目，來加載網絡資源並輕松觀看視頻的軟件。軟件中出現的圖片資源文字，都是由插件項目以及資源網站所提供。
軟件本身不提供視頻服務，使用漫畫資源時請遵循相關法律法規。

本軟件所提供下載的視頻資源，版權歸原作者所有。僅供學習交流之用，請復制、下載者遵循國家相關法律、法規，在未獲得版權擁有者授權之前，勿作它用；如因非法使用引起糾紛，壹切後果由使用者承擔。
  """,
  "credits": "貢獻者們",
  "can_not_open": "不能開啟 {0}",
  "framework": "Framework",
  "no_main_project": "無項目",
  "select_main_project_first": "設為主項目",
  "video_home": "熊視頻",
  "history": "歷史紀錄",
  "favorites": "收藏夾",
  "download_list": "下載列表",
  "manage_projects": "管理中心",
  "settings": "詳設細定",
  "search": "尋幽覓勝",
  "reverse_order": "逆向",
  "order": "正向",
  "libraries_hint": "克隆並選擇壹個項目後即可開始瀏覽內容。",
  "after_select_main": "已經選擇 {0} 為主項目,返回 {1} 即可開始瀏覽。",
  "need_overlay": "開啟 \"允許在其他應用的上層顯示\" 以便顯示小窗口播放器。",
  "sort_default": "默認排序",
  "sort_title": "標題排序",
  "sort_subtitle": "副標題排序",
  "waiting": "等待中...",
};